# Generated by scripts/terminal-gen.ts from .config/terminal.yaml - DO NOT EDIT
function GEN_N_0 { bunx just }
Set-Alias -Name just -Value GEN_N_0
function GEN_N_1 { bunx vitest }
Set-Alias -Name vitest -Value GEN_N_1
function GEN_N_2 { bunx @biomejs/biome }
Set-Alias -Name biome -Value GEN_N_2
function GEN_N_3 { bunx tsgo }
Set-Alias -Name tsgo -Value GEN_N_3
function GEN_N_4 { bunx knip }
Set-Alias -Name knip -Value GEN_N_4
function GEN_N_5 { bunx bunup }
Set-Alias -Name bunup -Value GEN_N_5
$env:ROOT_DIR = (git rev-parse --show-toplevel)