# Generated by scripts/terminal-gen.ts from .config/terminal.yaml - DO NOT EDIT
alias just='bunx just'
alias vitest='bunx vitest'
alias biome='bunx @biomejs/biome'
alias tsgo='bunx tsgo'
alias knip='bunx knip'
alias bunup='bunx bunup'
export ROOT_DIR="$(git rev-parse --show-toplevel)"