import { BunRuntime, BunServices } from "@effect/platform-bun"
import { YAML } from "bun"
import { Console, Effect, FileSystem, Path, Schema } from "effect"
import { Argument, Command, Flag } from "effect/unstable/cli"

// ─────────────────────────────────────────────────────────────────────────────
// Models & Schema
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @category models
 */
export const EnvValue = Schema.Struct({
  command: Schema.String,
})

/**
 * @category models
 */
export const TerminalSpec = Schema.Struct({
  alias: Schema.optionalKey(Schema.Record(Schema.String, Schema.String)),
  env: Schema.optionalKey(
    Schema.Record(Schema.String, Schema.Union([Schema.String, EnvValue])),
  ),
})
export type TerminalSpec = Schema.Schema.Type<typeof TerminalSpec>

/**
 * @category models
 */
export interface GenResult {
  readonly fileNameHint: string
  readonly source: string
}

/**
 * @category errors
 */
export class YamlError extends Schema.TaggedErrorClass<YamlError>()(
  "YamlError",
  {
    message: Schema.String,
    cause: Schema.Defect,
  },
) {}

// ─────────────────────────────────────────────────────────────────────────────
// Shell Generators
// ─────────────────────────────────────────────────────────────────────────────

const escapeSingle = (val: string) => val.replace(/'/g, "'\\''")
const escapeDouble = (val: string) => val.replace(/"/g, '\\"')
const escapePSFunction = (val: string) => val.replace(/}/g, "`}")

function generateFish(spec: TerminalSpec): GenResult {
  const lines: string[] = []

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`alias ${name}="${escapeDouble(value)}"`)
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`set -x ${name} "${escapeDouble(value)}"`)
      } else {
        lines.push(`set -x ${name} (${value.command})`)
      }
    }
  }

  return {
    fileNameHint: "gen-config.fish",
    source: lines.join("\n"),
  }
}

function generateBash(spec: TerminalSpec): GenResult {
  const lines: string[] = []

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`alias ${name}='${escapeSingle(value)}'`)
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`export ${name}="${escapeDouble(value)}"`)
      } else {
        lines.push(`export ${name}="$(${value.command})"`)
      }
    }
  }

  return {
    fileNameHint: "gen-bashrc.bash",
    source: lines.join("\n"),
  }
}

function generateZsh(spec: TerminalSpec): GenResult {
  const lines: string[] = []

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`alias ${name}='${escapeSingle(value)}'`)
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`export ${name}="${escapeDouble(value)}"`)
      } else {
        lines.push(`export ${name}="$(${value.command})"`)
      }
    }
  }

  return {
    fileNameHint: "gen-zshrc.zsh",
    source: lines.join("\n"),
  }
}

function generatePowerShell(spec: TerminalSpec): GenResult {
  const lines: string[] = []
  let idx = 0

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`function GEN_N_${idx} { ${escapePSFunction(value)} }`)
      lines.push(`Set-Alias -Name ${name} -Value GEN_N_${idx}`)
      idx++
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`$env:${name} = "${escapeDouble(value)}"`)
      } else {
        lines.push(`$env:${name} = (${value.command})`)
      }
    }
  }

  return {
    fileNameHint: "gen-profile.ps1",
    source: lines.join("\n"),
  }
}

const HEADER = (scriptPath: string, yamlPath: string) =>
  `# Generated by ${scriptPath} from ${yamlPath} - DO NOT EDIT\n`

// ─────────────────────────────────────────────────────────────────────────────
// CLI Definition
// ─────────────────────────────────────────────────────────────────────────────

const SHELL_MAP = {
  fish: { gen: generateFish, dir: "fish" },
  bash: { gen: generateBash, dir: "bash" },
  zsh: { gen: generateZsh, dir: "zsh" },
  powershell: { gen: generatePowerShell, dir: "powershell" },
} as const

type Shell = keyof typeof SHELL_MAP
const SHELLS = Object.keys(SHELL_MAP) as ReadonlyArray<Shell>

const configArg = Argument.file("config", { mustExist: true }).pipe(
  Argument.withDefault(".config/terminal.yaml"),
  Argument.withDescription("Path to terminal.yaml"),
)

const dryRunFlag = Flag.boolean("dry-run").pipe(
  Flag.withDescription(
    "Do not write to disk but console what would have been done",
  ),
)

const outputFlag = Flag.directory("output").pipe(
  Flag.withDefault(".config"),
  Flag.withDescription("Folder where to save the generated files"),
)

const shellsFlag = Flag.choice("shells", SHELLS).pipe(
  Flag.atLeast(0),
  Flag.withDescription("Terminals to generate for; default: all"),
)

/**
 * @category programs
 */
export const run = Command.make("terminal-gen", {
  config: configArg,
  dryRun: dryRunFlag,
  output: outputFlag,
  shells: shellsFlag,
}).pipe(
  Command.withDescription("Generates shell configurations from YAML"),
  Command.withHandler(({ config, dryRun, output, shells }) =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem
      const path = yield* Path.Path

      // Dynamic script path for header
      const scriptPath = path.relative(process.cwd(), Bun.main)

      // Read & Parse YAML
      const yamlText = yield* fs.readFileString(config)
      const parsed = yield* Effect.try({
        try: () => YAML.parse(yamlText),
        catch: (cause) =>
          new YamlError({ message: "Failed to parse YAML", cause }),
      })

      // Validate Schema
      const spec = yield* Schema.decodeUnknownEffect(TerminalSpec)(parsed)

      if (!(spec.alias || spec.env)) {
        yield* Console.warn("Warning: No aliases or env vars found in config.")
      }

      // Determine which shells to generate (deduplicated)
      const selectedShells =
        Array.isArray(shells) && shells.length > 0
          ? Array.from(new Set(shells))
          : SHELLS

      yield* Effect.forEach(
        selectedShells,
        (shell) =>
          Effect.gen(function* () {
            const entry = SHELL_MAP[shell as Shell]
            if (!entry) return

            const result = entry.gen(spec)
            const fullOutputDir = path.join(output, entry.dir)
            const filePath = path.join(fullOutputDir, result.fileNameHint)
            const content = HEADER(scriptPath, config) + result.source

            if (dryRun) {
              yield* Console.log(`\n[DRY RUN] Would write to: ${filePath}`)
              yield* Console.log(content)
            } else {
              yield* fs.makeDirectory(fullOutputDir, { recursive: true })
              yield* fs.writeFileString(filePath, content)
              yield* Console.log(`Generated: ${filePath}`)
            }
          }),
        { concurrency: "unbounded" },
      )
    }),
  ),
)

const layer = BunServices.layer

const main = run.pipe(Command.run({ version: "0.0.1" }), Effect.provide(layer))

BunRuntime.runMain(main)
