import { writeFileSync } from "node:fs"
import { YAML } from "bun"

const YAML_PATH = ".config/terminal.yaml"
const CONFIG_DIR = ".config"

interface Aliases {
  [key: string]: string
}

interface EnvValue {
  command?: string
  [key: string]: unknown
}

interface Env {
  [key: string]: string | EnvValue
}

interface TerminalSpec {
  alias?: Aliases
  env?: Env
}

interface GenResult {
  fileNameHint: string
  source: string
}

function generateFish(spec: TerminalSpec): GenResult {
  const lines: string[] = []

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`alias ${name}="${value}"`)
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`set -x ${name} "${value}"`)
      } else if (value.command) {
        lines.push(`set -x ${name} (${value.command})`)
      }
    }
  }

  return {
    fileNameHint: "gen-config.fish",
    source: lines.join("\n"),
  }
}

function generateBash(spec: TerminalSpec): GenResult {
  const lines: string[] = []

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`alias ${name}='${value}'`)
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`export ${name}="${value}"`)
      } else if (value.command) {
        lines.push(`export ${name}="$(${value.command})"`)
      }
    }
  }

  return {
    fileNameHint: "gen-bashrc.bash",
    source: lines.join("\n"),
  }
}

function generateZsh(spec: TerminalSpec): GenResult {
  const lines: string[] = []

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`alias ${name}='${value}'`)
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`export ${name}="${value}"`)
      } else if (value.command) {
        lines.push(`export ${name}="$(${value.command})"`)
      }
    }
  }

  return {
    fileNameHint: "gen-zshrc.zsh",
    source: lines.join("\n"),
  }
}

function generatePowerShell(spec: TerminalSpec): GenResult {
  const lines: string[] = []
  let idx = 0

  if (spec.alias) {
    for (const [name, value] of Object.entries(spec.alias)) {
      lines.push(`function GEN_N_${idx} { ${value} }`)
      lines.push(`Set-Alias -Name ${name} -Value GEN_N_${idx}`)
      idx++
    }
  }

  if (spec.env) {
    for (const [name, value] of Object.entries(spec.env)) {
      if (typeof value === "string") {
        lines.push(`$env:${name} = "${value}"`)
      } else if (value.command) {
        lines.push(`$env:${name} = (${value.command})`)
      }
    }
  }

  return {
    fileNameHint: "gen-profile.ps1",
    source: lines.join("\n"),
  }
}

const HEADER = (scriptPath: string, yamlPath: string) =>
  `# Generated by ${scriptPath} from ${yamlPath} - DO NOT EDIT\n`

async function run(yamlPath: string) {
  const text = await Bun.file(yamlPath).text()
  const spec = YAML.parse(text) as TerminalSpec

  const shells = [
    {
      dir: `${CONFIG_DIR}/fish`,
      gen: () => generateFish(spec),
    },
    {
      dir: `${CONFIG_DIR}/bash`,
      gen: () => generateBash(spec),
    },
    {
      dir: `${CONFIG_DIR}/zsh`,
      gen: () => generateZsh(spec),
    },
    {
      dir: `${CONFIG_DIR}/powershell`,
      gen: () => generatePowerShell(spec),
    },
  ]

  for (const shell of shells) {
    const result = shell.gen()
    const content = HEADER("scripts/terminal-gen.ts", yamlPath) + result.source
    writeFileSync(`${shell.dir}/${result.fileNameHint}`, content)
  }
}

run(YAML_PATH)
